version: '3'

services: 

  app:
    build: 
      context: node
      dockerfile: Dockerfile
    image: tmsdkr/node:latest      
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh node index.js
    networks: 
      - nodenet
    volumes: 
      - /usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    build: 
      context: ./
      dockerfile: db.Dockerfile  
    command: --innodb-use-native-aio=0
    image: tmsdkr/mysql:latest    
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet
  
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    image: tmsdkr/nginx:latest
    container_name: nginx
    networks: 
      - nodenet
    ports: 
      - "8080:80"
    

networks: 
  nodenet:
    driver: bridge
    name: nodenet